//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PittmarkProject.DbMain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Password
    {
        public int Id { get; set; }
        public Nullable<int> Id_admin { get; set; }
        public string Password1 { get; set; }
        public Nullable<System.DateTime> Insert_YMD { get; set; }
        public string Status { get; set; }
    
        public virtual Admin Admin { get; set; }
    }
}
