//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PittmarkProject.DbMain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPhamTrungBay
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> Delete_YMD { get; set; }
    }
}
